### ISSUE TITLE
Add pictures

### ISSUE THREAD

**Issue by marcogagino-22** [valerio-bozzolan/AcrylicPaint#26]
Add a picture as a canvas over which you can draw.

**Comment by horkana** [comment]
This would be useful to me too. 

I took a screenshot and hoped/expected I would be able to open it draw a quick mark on it using Acrylic

**Comment by toehead2001** [comment]
@valerio-bozzolan You mentioned the possibility of maybe using the some of the canvas code from Meme Generator. Before I investigate doing this, is the MIT license an issue? Does the GPL allow code under the MIT license to be used in the same project?

**Comment by valerio-bozzolan** [comment]
@toheaad2001 Thanks for this question, I really care about it.

The GNU General Public License it's the most-strictly copileft license for Free as in Freedom software. In the other g
hand think about the MIT license as a stupid «I don't really want to be killed of someone destroy his device with my software».

The GNU GPL also have this phrase, but in addition it care about a lot other things, so, we can legally see the GNU GPL an "extension of the MIT" because it simply respect the MIT conditions.

Aldo, in general, every software under a known Free license (e.g. MIT, Apache 2.0, WTFPL, Public Domain, GNU LGPL, FreeBSD, etc.) can be merged into a software under the GNU GPL, because the GNU GPL have so "restrictions" that it simply respects all the therms of theese licenses.

See this document: http://www.gnu.org/licenses/license-list.en.html

Look at this schema: http://www.gnu.org/licenses/quick-guide-gplv3-compatibility.png

Note that the reverse compatibily is generally NOT allowed, e.g. the MIT and the Apache 2 don't respect the 98% of the GNU GPL and so all the software in the world under the GNU GPL can't be used in a software that uses MIT.

I really want to care all the "four Freedoms" carried by the GNU GPL, so I really suggest you to merge wat you want to this source, in order to upgrade it's license to the GNU GPL :)

**Comment by toehead2001** [comment]
I also care about the four freedoms. :+1: I just was not clear on the compatibility. One more question to clarify. If I were to merge the MIT code from Meme Generator into this project, it would become GPL code?

**Comment by valerio-bozzolan** [comment]
@toehead2001 I usually save the integral text of a third-part license near original files and I force in these files the relative disclaimer. But F-Droid can exclude some folders from the build process so I think that in the future we can create something as:

DOCS/
|__ ./README.txt
\__ ./LICENSES/
___|_ ./MIT-license.txt
___|_./GNU-GPL-license.txt

In order to exclude that stuff from the APK package.

**Comment by vespadj** [comment]
request of enhancement: 
Menu / Open (.jpg; .png)
Menu / background (select or change color for backgroung)
or in alternative 
Menu / Fill (riempi)

ciao, vespadj

**Comment by TheOpenSourceNinja** [comment]
This sounds like a useful feature; any progress?

**Comment by valerio-bozzolan** [comment]
(Feel Free to do a pull request)

**Comment by TheOpenSourceNinja** [comment]
I'm working on it now :)

**Comment by valerio-bozzolan** [comment]
@TheOpenSourceNinja Great! I'm implementing the open-as feature over your code.

**Comment by valerio-bozzolan** [comment]
Closing this thanks to @TheOpenSourceNinja, adding also the "open from other apps" feature in 1c7a343218650423a5ab34f098753130793725b6.

**Comment by valerio-bozzolan** [comment]
Built by F-Droid recently.
