### ISSUE TITLE
Fix lint errors

### ISSUE THREAD

**Issue by krt16s** [valerio-bozzolan/AcrylicPaint#36]
I need to add `android { lintOptions { abortOnError false } }` to the build.gradle. However, setting abortOnError should only be disabled, if there is no other way and even if so, it should be controlled by upstream, since you know best, when the error requiring this are fixed.

So, either fix the lint issues or unset abortOnError for now.

**Comment by valerio-bozzolan** [comment]
I'm happy to help you in any way, but:

1. I don't know lint. What is the problem and how can I fix it? :sweat_smile:
2. I can't simply solve that with your `android { .. }` because then Android Studio says that I miss the `android` plugin. (eh.. uh.. wut?)

Trust me, I don't know what I'm talking about.

**Comment by krt16s** [comment]
Lint: See https://developer.android.com/tools/help/lint.html, so `Analyze > Inspect Code` should invoke it from AS.

Plugin: I was talking about app/build.gradle here, just adding it at the bottom should work.

**Comment by valerio-bozzolan** [comment]
I think that it's done with 89074c68a84c1d69add4a192fd1c0779285a0586.
